# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74771a404970a3732a8ef7f8ccb5d52a51141a482363169634884c0c19c2d45eacfba69673fd3f7bb455f1b60c996a8f77ad697994fca8ef6cd6935aaa854ba4

test:
  secret_key_base: 8f109a57e7052b33c0588a27f6bdceb06e370de475fb18ba74e8e766e62027a9723a9311718bb9d094f8fcfb9c6fe43b87669df8611c2f41db2ae9f1f9f12a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
